---
- name: Add backports
  apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main contrib"
    state: present
    filename: backports

- name: Use systemd from backports
  copy:
    src: 01_systemd
    dest: /etc/apt/preferences.d/01_systemd
    owner: root
    group: root
    mode: 0644

#- name: Install software from Backports
#  apt:
#    name:
#      - golang-go
#    state: present
#    default_release: {{ ansible_distribution_release }}-backports
#    update_cache: true
