---
- name: Add backports
  apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main"
    state: present
    filename: backports
  tags: ['apt']

#- name: Install software from Backports
#  apt:
#    name:
#      - golang-go
#    state: present
#    default_release: {{ ansible_distribution_release }}-backports
#    update_cache: true
#  tags: ['apt']
