---
- name: Support Bluetooth speakers
  lineinfile:
    path: /etc/bluetooth/main.conf
    line: "Experimental = true"
    insertafter: "^#Experimental = false"
  tags: ['bluetooth']

- name: adding user to bluetooth group
  user:
    name: "{{ target_user }}"
    groups: bluetooth
    append: yes
  become: yes
  when: target_user != "root"
  tags: ['bluetooth']
