---
- name: Support Bluetooth speakers
  lineinfile:
    path: /etc/bluetooth/main.conf
    line: "Experimental = true"
    insertafter: "^#Experimental = false"

- name: Support Bluetooth speakers #2
  lineinfile:
    path: /etc/bluetooth/main.conf
    line: "ControllerMode = bredr"
    insertafter: "^#ControllerMode = dual"

- name: adding user to bluetooth group
  user:
    name: "{{ target_user }}"
    groups: bluetooth
    append: yes
  become: yes
  when: target_user != "root"
