---
- name: Restart NFS
  systemd:
    name: nfs-server
    state: restarted

- name: Restart Samba
  systemd:
    name: smbd
    state: restarted

- name: Disable nmbd
  systemd:
    name: nmbd
    state: stopped
    enabled: false
  ignore_errors: true
