---
- name: Create export directory
  file:
    path: "{{ export_directory }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

# - include_tasks: nfs.yml
- include_tasks: samba.yml
