---
- name: Install Samba packages
  apt:
    name:
      - samba
    state: present
  tags: ['apt', 'samba']

- name: Configure smb.conf
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart Samba
  tags: ['samba']

- name: Remove homes from Samba
  ini_file:
    path: /etc/samba/smb.conf
    section: homes
    state: absent
  notify: Restart Samba
  tags: ['samba']

- name: Remove printers from Samba
  ini_file:
    path: /etc/samba/smb.conf
    section: printers
    state: absent
  notify: Restart Samba
  tags: ['samba']

- name: Remove print$ from Samba
  ini_file:
    path: /etc/samba/smb.conf
    section: print$
    state: absent
  notify: Restart Samba
  tags: ['samba']
