---
#- name: Update cache
#  apt:
#    update_cache: yes
#  tags: ['apt']

- name: Install packages
  apt:
    name:
      - avahi-utils
      - bpfcc-tools
      - bridge-utils
      - cifs-utils
      - cryptsetup
      - curl
      - dnsutils
      - e2fsprogs
      - fakeroot
      - gawk
      - gh
      - git
      - gnutls-bin
      - iptables
      - jq
      - libarchive-tools
      - libbsd-dev
      - libnss3-tools
      - lsscsi
      - make
      - mc
      - mtr
      - netcat-openbsd
      - net-tools
      - nmap
      - patch
      - podman
      - procinfo
      - pulseaudio-module-bluetooth
      - python3-dev
      - python3-pip
      - rclone
      - rsync
      - screen
      - sg3-utils
      - socat
      - strace
      - traceroute
      - unzip
      - vim
      - vlc
      - wget
      - whois
      - xfsprogs
    state: present
  tags: ['apt']

- name: Uninstall packages
  apt:
    name:
      - chromium-browser
      - cups
      - firefox
      - libreoffice-*
      - qemu-utils
      - rhythmbox
      - saned
      - sssd
      - thunderbird
    state: absent
    purge: true
  tags: ['apt']

- name: Run apt autoremove
  apt:
    autoremove: yes
    purge: true
  tags: ['apt']
