---
- name: Get dpkg architecture
  command: "dpkg --print-architecture"
  register: dpkg_architecture
  changed_when: false

- name: Install Docker repo
  block:
    - name: Install Docker gpg key
      get_url:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        dest: /etc/apt/keyrings/docker.asc
        checksum: sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570

    - name: Add Docker repo
      apt_repository:
        repo: "deb [arch={{ dpkg_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

- name: Install Docker packages
  apt:
    name:
      - docker-ce
    state: present
