---
- name: Make vim work
  copy:
    src: vimrc
    dest: /root/.vimrc
    owner: root
    group: root
    mode: 0644
  tags: ['vim']

- name: Support Bluetooth speakers
  lineinfile:
    path: /etc/bluetooth/main.conf
    line: "Experimental = true"
    insertafter: "^#Experimental = false"
  tags: ['bluetooth']

- name: adding user ricardo to group libvirt
  user:
    name: ricardo
    groups: bluetooth
    append: yes
  become: yes
  tags: ['bluetooth']
