---
- name: Ensure .ssh folder exists
  file:
    path: /root/.ssh
    owner: root
    group: root
    mode: 0700
  tags: ['ssh']

- name: Add custom openSSH configuration
  copy:
    src: ssh/custom.conf
    dest: /etc/ssh/sshd_config.d/custom.conf
    owner: root
    group: root
    mode: 0600
  tags: ['ssh']
