---
- name: Add custom openSSH configuration
  copy:
    src: ssh/custom.conf
    dest: /etc/ssh/sshd_config.d/custom.conf
    owner: root
    group: root
    mode: 0600

- name: Secure permissions for /etc/ssh/sshd_config.d
  file:
    path: /etc/ssh/sshd_config.d
    state: directory
    owner: root
    group: root
    mode: '0500'

- name: Add AllowUsers configuration
  copy:
    dest: /etc/ssh/sshd_config.d/users.conf
    content: |
      AllowUsers root {{ target_user }}
    owner: root
    group: root
    mode: '0600'
