---
- name: Pin for ZFS packages
  copy:
    src: 90_zfs
    dest: /etc/apt/preferences.d/90_zfs
    owner: root
    group: root
    mode: 0644

- name: Install ZFS packages
  apt:
    name:
      - zfs-dkms
      - zfs-initramfs
      - zfs-zed
      - zfsutils-linux
    install_recommends: false
    update_cache: true
    state: present
